"""scom-v's ComfyUI custom node, installed at backend startup.

The node source below is written to ``userdata/custom_nodes/scomv_taeh3_preview.py``
and injected via the ``custom_nodes`` entry of extra_model_paths.yaml, so the
managed ComfyUI tree itself is never modified (survives version bumps).

The node registers no graph nodes — importing it monkeypatches
``latent_preview.get_previewer`` so that MiniMax H3 sampling previews use the
community taeh3 tiny decoder (models/vae_approx/taeh3.safetensors) instead of
the built-in Latent2RGB projection. ComfyUI core has no TAE wired up for H3,
and its TAESD/TAEHV loaders cannot build taeh3's flat 96-wide/4-upsample
architecture, hence the custom loader here. Decode cost is ~30 ms per step on
an RTX 4090 (vs ~7 s/step sampling) — negligible.
"""
from __future__ import annotations

from pathlib import Path

from . import config

NODE_SOURCE = '''"""scom-v custom node (auto-generated by the scom-v app; do not edit).

MiniMax H3 のサンプリングプレビューを taeh3 (tiny decoder) に差し替える。
models/vae_approx/taeh3*.safetensors が無いときは何もしない（Latent2RGB の
まま）。グラフ用ノードは登録しない。
"""
import logging

import torch
import torch.nn as nn

import comfy.latent_formats
import comfy.model_management
import comfy.utils
import folder_paths
import latent_preview
from comfy.taesd.taesd import Block, Clamp, conv


def _build_flat_decoder(sd):
    """Flat TAESD-style decoder ("N.xxx" keys) -> nn.Sequential.

    taeh3 は本体の Decoder（64ch固定・3段アップサンプル）と形が合わないため、
    state dict の添字からアーキテクチャを復元する: ``N.conv.0.weight`` は
    Block、``N.weight`` は conv、欠番はパラメータ無し層（0=Clamp, 2=ReLU,
    他=Upsample）。
    """
    by_index = {}
    for k, v in sd.items():
        head, _, rest = k.partition(".")
        if not head.isdigit():
            raise ValueError(f"unexpected key '{k}'")
        by_index.setdefault(int(head), {})[rest] = v
    modules = []
    for i in range(max(by_index) + 1):
        entry = by_index.get(i)
        if entry is None:
            modules.append(Clamp() if i == 0 else nn.ReLU() if i == 2
                           else nn.Upsample(scale_factor=2.0))
        elif "conv.0.weight" in entry:
            w = entry["conv.0.weight"]
            modules.append(Block(w.shape[1], w.shape[0]))
        elif "weight" in entry:
            w = entry["weight"]
            modules.append(conv(w.shape[1], w.shape[0], bias="bias" in entry))
        else:
            raise ValueError(f"unrecognized module at index {i}: {sorted(entry)}")
    return nn.Sequential(*modules)


class _TAEH3Previewer(latent_preview.LatentPreviewer):
    """動画ラテントは先頭 / 1/3 / 2/3 / 末尾の4フレームを 2x2 グリッド表示。

    H3 は全フレームを一括でノイズ除去するため、どの時点のフレームも同じ
    ラテントからデコードできる（4フレームで約120ms/ステップ）。
    """

    def __init__(self, model, device, dtype):
        self.model = model
        self.device = device
        self.dtype = dtype

    def _frame(self, x):
        """[B, C, h, w] -> HWC [0, 1]（taeh3 の出力は TAE 系の慣習で [0,1]）。"""
        x = x[:1, :24].to(device=self.device, dtype=self.dtype)
        return self.model(x)[0].movedim(0, 2)

    def decode_latent_to_preview(self, x0):
        with torch.no_grad():
            if x0.ndim == 5 and x0.shape[2] > 1:
                t = x0.shape[2]
                idx = [0, (t - 1) // 3, ((t - 1) * 2) // 3, t - 1]
                f = [self._frame(x0[:, :, i]) for i in idx]
                gap_v = torch.zeros_like(f[0][:, :2])    # 2px の区切り線
                top = torch.cat([f[0], gap_v, f[1]], dim=1)
                bottom = torch.cat([f[2], gap_v, f[3]], dim=1)
                gap_h = torch.zeros_like(top[:2])
                img = torch.cat([top, gap_h, bottom], dim=0)
            else:
                if x0.ndim == 5:
                    x0 = x0[:, :, 0]
                img = self._frame(x0)
        return latent_preview.preview_to_image(img, do_scale=False)


_cache = {"path": None, "previewer": None}


def _taeh3_previewer():
    files = [fn for fn in folder_paths.get_filename_list("vae_approx")
             if fn.startswith("taeh3")]
    if not files:
        return None
    path = folder_paths.get_full_path("vae_approx", files[0])
    if _cache["path"] == path:
        return _cache["previewer"]
    previewer = None
    try:
        sd = comfy.utils.load_torch_file(path, safe_load=True)
        device = comfy.model_management.vae_device()
        dtype = comfy.model_management.vae_dtype(
            device, [torch.float16, torch.bfloat16])
        model = _build_flat_decoder(sd)
        model.load_state_dict(sd)
        model = model.eval().to(device=device, dtype=dtype)
        previewer = _TAEH3Previewer(model, device, dtype)
        # 形の不一致はここで検出する（サンプリング中に落とさない）。
        previewer.decode_latent_to_preview(torch.zeros(1, 24, 2, 2))
        logging.info(f"[scom-v] H3 preview via taeh3: {path}")
    except Exception as e:  # noqa: BLE001
        logging.warning(f"[scom-v] taeh3 preview unavailable: {e}")
        previewer = None
    _cache["path"] = path
    _cache["previewer"] = previewer
    return previewer


_orig_get_previewer = latent_preview.get_previewer


def _get_previewer(device, latent_format):
    from comfy.cli_args import args, LatentPreviewMethod
    if (isinstance(latent_format, comfy.latent_formats.MiniMaxH3Video)
            and args.preview_method != LatentPreviewMethod.NoPreviews):
        p = _taeh3_previewer()
        if p is not None:
            return p
    return _orig_get_previewer(device, latent_format)


latent_preview.get_previewer = _get_previewer

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}
'''


def ensure_custom_nodes(paths: config.AppPaths) -> Path:
    """Write (or refresh) the scom-v custom node file; return its directory."""
    node_dir = paths.user_data / "custom_nodes"
    node_dir.mkdir(parents=True, exist_ok=True)
    node_file = node_dir / "scomv_taeh3_preview.py"
    # Rewrite only on change so an unchanged app doesn't churn the mtime.
    try:
        if node_file.read_text(encoding="utf-8") == NODE_SOURCE:
            return node_dir
    except OSError:
        pass
    node_file.write_text(NODE_SOURCE, encoding="utf-8")
    return node_dir
