"""scom's ComfyUI custom nodes, installed at backend startup.

The node source below is written to ``userdata/custom_nodes/scom_merge.py``
and injected via the ``custom_nodes`` entry of extra_model_paths.yaml, so the
managed ComfyUI tree itself is never modified (survives version bumps).

ScomMergeModel materializes a weighted average of N diffusion models as a
plain state dict in main memory. Two strategies, selected per prompt:

  * batch (default): all sources open at once, each tensor combined in fp32
    in a single pass — best precision, but page cache grows to N models.
  * low_memory: one source open at a time, folded into a bf16 accumulator
    (incremental weighted mean) — peak RAM ~ result + one source, at the cost
    of a per-step bf16 rounding.

Either way the result is returned as a normal MODEL: ComfyUI's node-output
cache keeps it in RAM across prompts (same node id + inputs = reused, no
re-merge) and model management moves it VRAM<->RAM like any other model.

``quantize`` selects the output precision: "" keeps bf16, "fp8" re-quantizes
Linear weights to per-tensor scaled float8_e4m3fn (Comfy-Org "fp8_scaled"
layout), "int8_convrot" produces ComfyUI v0.27's native INT8 ConvRot format
(group-wise Hadamard rotation + per-row INT8; only the main DiT ``blocks.``
Linear layers, matching public INT8-ConvRot checkpoints), "int4_convrot"
produces an int4/int8 hybrid built on the ConvRot W4A4 format added after
v0.27 (packed 4-bit weights, group-64 scales, needs comfy-kitchen >=
0.2.17): q/k/v/up projections go int4 with nearest rounding, the
error-prone output-side projections (attn output / MLP down) go int8, adaLN
modulation and anima's llm_adapter stay high precision, and the matmul is
pinned to int8 via ``linear_dtype`` — full 4-bit compute and stochastic
rounding were each verified to visibly degrade anima-sized models.
"int4_convrot_full" is the same minus the int8 exemption: every eligible
layer goes int4 (smallest file; fine on krea2-sized models, visibly lossy
on small ones). ``save_to`` additionally writes the merged state dict as a
safetensors file into the app's diffusion_models folder.
"""
from __future__ import annotations

from pathlib import Path

from . import config

NODE_SOURCE = '''"""scom custom nodes (auto-generated by the scom app; do not edit)."""
import gc
import json
import logging
import os
import threading
import time

import psutil
import torch

import comfy.model_management
import comfy.model_patcher
import comfy.quant_ops
import comfy.sd
import comfy.utils
import folder_paths
from comfy.float import stochastic_rounding

_PREFIX = "diffusion_model."
# Quantization side-car keys; excluded from the canonical (dequantized) view.
_AUX_SUFFIXES = (".comfy_quant", ".weight_scale", ".weight_scale_2",
                 ".input_scale", ".scale_weight", ".scale_input")
_FP8_MAX = 448.0  # largest normal value of float8_e4m3fn


def _canonical_keys(patcher):
    keys = set()
    for k in patcher.model_state_dict(_PREFIX):
        if k.endswith(_AUX_SUFFIXES) or k == _PREFIX + "scaled_fp8":
            continue
        keys.add(k)
    return keys


def _dequant(patcher, key):
    """Return the dequantized weight for ``key`` (any source quant format)."""
    weight, _set_func, convert_func = comfy.model_patcher.get_key_weight(
        patcher.model, key)
    if convert_func is not None:
        weight = convert_func(weight, inplace=False)
    return weight


def _is_linear(patcher, key):
    try:
        mod = comfy.utils.get_attr(patcher.model, key.rsplit(".", 1)[0])
    except AttributeError:
        return False
    # Covers torch.nn.Linear, comfy ops Linear and quantized Linear variants.
    return "Linear" in type(mod).__name__


def _load_patcher(name):
    path = folder_paths.get_full_path("diffusion_models", name)
    if path is None:
        raise ValueError("モデルが見つかりません: {}".format(name))
    logging.info("scom merge: loading {}".format(name))
    return comfy.sd.load_diffusion_model(path)


QUANT_MODES = ("", "fp8", "int8_convrot", "int4_convrot",
               "int4_convrot_full")
_CONVROT_GROUP = 256
_INT4_QUANT_GROUP = 64  # scale group of the packed int4 (convrot_w4a4) layout
# The default int4 mode is a mix: the second/output matmul of each attention
# and MLP (down/output projections) measured the highest int4 weight error on
# anima (0.16-0.29 vs 0.15 elsewhere) and stays int8. Names cover anima
# (output_proj/layer2) and krea2 (wo/down); q/k/v/up/gate go int4.
# "int4_convrot_full" skips this exemption (smallest file; big models only).
_INT4_KEEP_INT8 = ("output_proj", "o_proj", "layer2", "wo", "down")


def _int4_output_side(layer):
    """Output-side projection (kept int8 in the hybrid int4 mode)?"""
    if layer.rsplit(".", 1)[-1] in _INT4_KEEP_INT8:
        return True
    # SDXL naming: attention output = "...attn.to_out.0",
    # feed-forward second matmul = "...ff.net.2".
    return ".to_out." in layer + "." or layer.endswith("ff.net.2")


def _quant_eligible(mode, key, bare, quantizable, ndim, in_features):
    """Is this tensor a quantization target for the chosen mode?"""
    if mode not in QUANT_MODES:
        raise ValueError("不明な量子化形式です: {}".format(mode))
    if not mode or key not in quantizable or ndim != 2:
        return False
    if mode in ("int8_convrot", "int4_convrot", "int4_convrot_full"):
        # Conservative policy matching public ConvRot checkpoints: only the
        # main DiT blocks (krea2: blocks.*, anima: net.blocks.*); the
        # sensitive embed/final/txt layers stay high precision. The Hadamard
        # rotation also needs in_features divisible by the group size (256,
        # a multiple of the int4 scale group 64).
        if "blocks." not in bare or in_features % _CONVROT_GROUP != 0:
            return False
        # Text-conditioning paths stay high precision like the official
        # checkpoints (Comfy-Org's krea2 int8 leaves all 32 txtfusion
        # linears at bf16; anima's llm_adapter is its equivalent). Their
        # names contain "blocks." too, hence the explicit exclusion.
        if "txtfusion" in bare or bare.startswith("llm_adapter."):
            return False
        if mode.startswith("int4_convrot"):
            # int4 is far less forgiving than int8 (verified: quantizing
            # these produces pure noise). Public ConvRot checkpoints keep
            # the adaLN modulation layers high precision.
            if "adaln" in bare:
                return False
        return True
    return True


def _quantize_out(bare, acc32, mode):
    """Quantize one merged fp32 tensor; return (sd entries, layer conf)."""
    layer = bare[:-len(".weight")]
    seed = comfy.utils.string_to_seed(bare) or 1
    if mode == "fp8":
        # Per-tensor scaled float8_e4m3fn (Comfy-Org fp8_scaled layout).
        scale = torch.clamp(acc32.abs().amax(), min=1e-8) / _FP8_MAX
        q = stochastic_rounding(acc32 / scale, torch.float8_e4m3fn, seed=seed)
        return ({bare: q, layer + ".weight_scale": scale.to(torch.float32)},
                {"format": "float8_e4m3fn",
                 "full_precision_matrix_mult": True})
    # ".attn2.to_k" は int4 にしない（両 int4 モード共通）: ComfyUI の
    # SD-UNet アーキテクチャ判定が attn2.to_k.weight の形状から context_dim
    # を読むため、パック形状 (K が半分) だと判定不能になり
    # "'NoneType' object has no attribute 'quant_config'" で落ちる。
    if (mode.startswith("int4_convrot")
            and ".attn2.to_k" not in layer
            and (mode == "int4_convrot_full"
                 or not _int4_output_side(layer))):
        # convrot_w4a4: Hadamard rotation + packed 4-bit weights with
        # group-64 scales (post-v0.27 format; comfy-kitchen >= 0.2.17).
        # In the hybrid "int4_convrot" mode the output-side projections
        # (see _INT4_KEEP_INT8) fall through to the int8 branch below;
        # "int4_convrot_full" quantizes every eligible layer to int4.
        layout = getattr(comfy.quant_ops, "TensorCoreConvRotW4A4Layout", None)
        if layout is None or not hasattr(layout, "quantize"):
            raise RuntimeError(
                "int4 ConvRot 量子化にはこの ComfyUI / comfy_kitchen が"
                "対応していません")
        # linear_dtype "int8": weights are stored packed int4 (1/4 size) but
        # the matmul runs int8 (W4A8). Full W4A4 (activations also 4-bit,
        # the loader default on int4-capable GPUs) was verified to produce
        # pure noise on anima-sized models, while W4A8 matches int8 speed.
        # stochastic_rounding=0 -> nearest rounding: measured 0.21 -> 0.15
        # relative weight error on anima; at 4 bits the extra stochastic
        # noise is clearly visible in the output.
        qdata, params = layout.quantize(
            acc32, convrot_groupsize=_CONVROT_GROUP,
            quant_group_size=_INT4_QUANT_GROUP, stochastic_rounding=0,
            linear_dtype="int8")
        return ({bare: qdata, layer + ".weight_scale": params.scale},
                {"format": "convrot_w4a4",
                 "convrot_groupsize": _CONVROT_GROUP,
                 "linear_dtype": "int8"})
    # int8_convrot: group-wise Hadamard rotation + per-row INT8 (ComfyUI
    # v0.27 native format; kernels from comfy_kitchen, eager path on CPU).
    layout = getattr(comfy.quant_ops, "TensorWiseINT8Layout", None)
    if layout is None or not hasattr(layout, "quantize"):
        raise RuntimeError(
            "int8 ConvRot 量子化にはこの ComfyUI / comfy_kitchen が対応していません")
    # stochastic_rounding=0 -> nearest rounding, matching the official
    # Comfy-Org int8 checkpoints (stochastic measured 1.44x their error).
    qdata, params = layout.quantize(
        acc32, is_weight=True, per_channel=True, convrot=True,
        convrot_groupsize=_CONVROT_GROUP, stochastic_rounding=0)
    return ({bare: qdata, layer + ".weight_scale": params.scale},
            {"format": "int8_tensorwise", "convrot": True,
             "convrot_groupsize": _CONVROT_GROUP})


def _arch_error(first_name, other_name):
    return ValueError(
        "アーキテクチャの異なるモデルはマージできません: "
        "{} と {}".format(first_name, other_name))


# ---------------------------------------------------------------------------
# Pin cache: merged models kept in RAM under OUR control.
#
# ComfyUI's default RAM-pressure output cache treats ModelPatchers from past
# prompts as the first thing to evict (caching.py: "old ModelPatchers are the
# first to go"), so merged models would rarely survive switching recipes.
# The node therefore keeps its own {key -> model} dict: on a hit the node
# returns instantly without re-merging, regardless of ComfyUI's cache. RAM
# safety is preserved by an LRU sweep that frees the least-recently-used
# pinned models while system RAM is tight.
# ---------------------------------------------------------------------------
_PIN_LOCK = threading.Lock()
_PIN_CACHE = {}  # key -> {"model": ModelPatcher, "ts": float}
# Keep at least this much system RAM available (mirrors the app-side note:
# "RAMが逼迫してきたときに使われていないモデルから自動で削除").
_PIN_MIN_AVAILABLE = max(4e9, psutil.virtual_memory().total * 0.10)


def _pin_key(recipe, quantize, low_memory):
    return json.dumps([recipe, quantize, bool(low_memory)])


def _evict_pins_locked():
    entries = sorted(_PIN_CACHE.items(), key=lambda kv: kv[1]["ts"])
    freed = False
    while (len(entries) > 1
           and psutil.virtual_memory().available < _PIN_MIN_AVAILABLE):
        key, _e = entries.pop(0)
        del _PIN_CACHE[key]
        freed = True
        logging.info("scom merge: released a pinned merged model (RAM pressure)")
    if freed:
        gc.collect()


def _register_routes():
    """Management API for the scom app: query / release pinned models."""
    from aiohttp import web
    from server import PromptServer
    routes = PromptServer.instance.routes

    @routes.get("/scom/merges")
    async def scom_merges(request):
        with _PIN_LOCK:
            return web.json_response({"pinned": list(_PIN_CACHE.keys())})

    @routes.post("/scom/merge_release")
    async def scom_merge_release(request):
        data = await request.json()
        with _PIN_LOCK:
            if data.get("all"):
                released = len(_PIN_CACHE)
                _PIN_CACHE.clear()
            else:
                key = _pin_key(data.get("recipe", "[]"),
                               data.get("quantize", ""),
                               data.get("low_memory", False))
                released = 1 if _PIN_CACHE.pop(key, None) is not None else 0
        gc.collect()
        return web.json_response({"released": released})


try:
    _register_routes()
except Exception:  # noqa: BLE001 - the node still works without the routes
    logging.exception("scom: failed to register /scom/* routes")


def _patch_int8_rowwise():
    """Load third-party "int8_rowwise" checkpoints (e.g. Krea int8-convrot
    releases). Their tensors are identical to the supported int8_tensorwise
    per-channel layout (int8 weight [N,K] + fp32 scale [N,1], optional
    ConvRot); only the comfy_quant format string differs, so rewrite it
    before the state dict reaches ComfyUI's quantized-module loader."""
    orig = comfy.sd.load_diffusion_model_state_dict
    if getattr(orig, "_scom_int8_rowwise", False):
        return

    def patched(sd, *args, **kwargs):
        for k in list(sd):
            if not k.endswith("comfy_quant"):
                continue
            try:
                conf = json.loads(bytes(sd[k].numpy().tobytes()))
            except (ValueError, AttributeError, RuntimeError):
                continue
            if not isinstance(conf, dict) or conf.get("format") != "int8_rowwise":
                continue
            conf["format"] = "int8_tensorwise"
            conf.pop("per_row", None)
            sd[k] = torch.tensor(
                list(json.dumps(conf).encode("utf-8")), dtype=torch.uint8)
        return orig(sd, *args, **kwargs)

    patched._scom_int8_rowwise = True
    comfy.sd.load_diffusion_model_state_dict = patched


try:
    _patch_int8_rowwise()
except Exception:  # noqa: BLE001 - only int8_rowwise files are affected
    logging.exception("scom: failed to patch int8_rowwise support")


class ScomMergeModel:
    """Materialize a weighted average of N diffusion models in main memory."""

    @classmethod
    def INPUT_TYPES(cls):
        return {"required": {
            # JSON: [["file.safetensors", weight], ...] (relative weights)
            "recipe": ("STRING", {"default": "[]", "multiline": True}),
            # "" (no quantization) | "fp8" | "int8_convrot"
            # | "int4_convrot" (hybrid) | "int4_convrot_full" (all int4)
            "quantize": ("STRING", {"default": ""}),
            # True: one source at a time (bf16 accumulator, low RAM);
            # False: all sources at once (fp32 combine, best precision).
            "low_memory": ("BOOLEAN", {"default": False}),
            # Optional filename; when set the merged model is also written to
            # the diffusion_models folder as a safetensors file.
            "save_to": ("STRING", {"default": ""}),
        }}

    RETURN_TYPES = ("MODEL",)
    FUNCTION = "merge"
    OUTPUT_NODE = True  # allow merge-only prompts (no downstream sampler)
    CATEGORY = "scom"

    def merge(self, recipe, quantize="", low_memory=False, save_to=""):
        entries = json.loads(recipe)
        if not isinstance(entries, list) or len(entries) < 1:
            raise ValueError("マージには1個以上のモデルが必要です")
        weights = [float(w) for _n, w in entries]
        if any(w <= 0 for w in weights):
            raise ValueError("マージ比率は正の数値で指定してください")
        if quantize not in QUANT_MODES:
            raise ValueError("不明な量子化形式です: {}".format(quantize))

        # Pinned model already in RAM? Return it without re-merging. (Save
        # runs always rebuild: the state dict is needed to write the file.)
        key = _pin_key(recipe, quantize, low_memory)
        if not save_to:
            with _PIN_LOCK:
                hit = _PIN_CACHE.get(key)
                if hit is not None:
                    hit["ts"] = time.time()
                    logging.info("scom merge: reusing pinned merged model")
                    return (hit["model"],)

        if low_memory:
            out_sd, quant_layers = self._merge_sequential(
                entries, weights, quantize)
        else:
            out_sd, quant_layers = self._merge_batch(
                entries, weights, quantize)

        if save_to:
            self._save(out_sd, quant_layers, save_to)

        # comfy_quant side-car keys make the loader treat quantized layers as
        # such (same result as loading an fp8_scaled checkpoint from disk).
        for layer, conf in quant_layers.items():
            out_sd[layer + ".comfy_quant"] = torch.tensor(
                list(json.dumps(conf).encode("utf-8")), dtype=torch.uint8)
        model = comfy.sd.load_diffusion_model_state_dict(out_sd)
        if model is None:
            raise RuntimeError("マージ結果のモデル構築に失敗しました")

        with _PIN_LOCK:
            _PIN_CACHE[key] = {"model": model, "ts": time.time()}
            _evict_pins_locked()
        return (model,)

    @staticmethod
    def _merge_batch(entries, weights, quantize):
        """All sources open at once; each tensor combined in fp32, one pass."""
        total = sum(weights)
        patchers = [_load_patcher(name) for name, _w in entries]

        keys = _canonical_keys(patchers[0])
        for (name, _w), p in zip(entries[1:], patchers[1:]):
            if _canonical_keys(p) != keys:
                raise _arch_error(entries[0][0], name)
        quantizable = set()
        if quantize:
            quantizable = {k for k in keys
                           if k.endswith(".weight")
                           and _is_linear(patchers[0], k)}

        out_sd = {}
        quant_layers = {}
        pbar = comfy.utils.ProgressBar(len(keys))
        for k in sorted(keys):
            comfy.model_management.throw_exception_if_processing_interrupted()
            bare = k[len(_PREFIX):]
            first = _dequant(patchers[0], k)
            if not first.dtype.is_floating_point:
                out_sd[bare] = first.clone()  # non-float buffers: copy as-is
                pbar.update(1)
                continue
            # Weighted average in fp32 (a single accumulator per tensor; the
            # sources are only read, never modified in place).
            acc = first.to(torch.float32) * (weights[0] / total)
            for p, w in zip(patchers[1:], weights[1:]):
                acc.add_(_dequant(p, k).to(torch.float32), alpha=w / total)

            in_features = acc.shape[-1] if acc.ndim == 2 else 0
            if _quant_eligible(quantize, k, bare, quantizable, acc.ndim,
                               in_features):
                sd_entries, conf = _quantize_out(bare, acc, quantize)
                out_sd.update(sd_entries)
                quant_layers[bare[:-len(".weight")]] = conf
            else:
                out_sd[bare] = acc.to(torch.bfloat16)
            pbar.update(1)

        del patchers  # release the mmap-backed source models
        return out_sd, quant_layers

    @staticmethod
    def _merge_sequential(entries, weights, quantize):
        """One source open at a time, folded into a bf16 accumulator.

        Incremental weighted mean: folding model k with ratio w_k / S_k (S_k =
        cumulative weight) telescopes to the exact weighted average; the only
        loss vs the batch path is the bf16 round-off of the accumulator after
        each step. Peak RAM ~ accumulator (bf16) + one source.
        """
        acc = {}
        keys = None
        quantizable = set()
        running = 0.0
        pbar = None
        for i, ((name, _w), w) in enumerate(zip(entries, weights)):
            patcher = _load_patcher(name)
            k_set = _canonical_keys(patcher)
            if keys is None:
                keys = k_set
                pbar = comfy.utils.ProgressBar(len(keys) * len(entries))
                if quantize:
                    quantizable = {k for k in keys
                                   if k.endswith(".weight")
                                   and _is_linear(patcher, k)}
            elif k_set != keys:
                raise _arch_error(entries[0][0], name)

            ratio = w / (running + w)  # new model's share at this step
            for k in sorted(keys):
                comfy.model_management.throw_exception_if_processing_interrupted()
                t = _dequant(patcher, k)
                if not t.dtype.is_floating_point:
                    if i == 0:
                        acc[k] = t.clone()
                elif i == 0:
                    acc[k] = t.to(torch.bfloat16, copy=True)
                else:
                    a = acc[k].to(torch.float32)
                    a.mul_(1.0 - ratio).add_(t.to(torch.float32), alpha=ratio)
                    acc[k] = a.to(torch.bfloat16)
                pbar.update(1)
            running += w
            del patcher
            gc.collect()  # promptly drop this source's modules / mmap pages

        out_sd = {}
        quant_layers = {}
        for k in sorted(keys):
            bare = k[len(_PREFIX):]
            t = acc.pop(k)  # pop: free the bf16 copy once converted
            in_features = t.shape[-1] if t.ndim == 2 else 0
            if (t.dtype.is_floating_point
                    and _quant_eligible(quantize, k, bare, quantizable,
                                        t.ndim, in_features)):
                sd_entries, conf = _quantize_out(bare, t.to(torch.float32),
                                                 quantize)
                out_sd.update(sd_entries)
                quant_layers[bare[:-len(".weight")]] = conf
            else:
                out_sd[bare] = t
        return out_sd, quant_layers

    @staticmethod
    def _save(out_sd, quant_layers, save_to):
        name = os.path.basename(save_to).strip()
        if not name:
            raise ValueError("保存ファイル名が不正です")
        if not name.endswith(".safetensors"):
            name += ".safetensors"
        out_dir = folder_paths.get_folder_paths("diffusion_models")[0]
        os.makedirs(out_dir, exist_ok=True)
        path = os.path.join(out_dir, name)
        # Same on-disk layout as Comfy-Org fp8_scaled releases: quantization
        # info lives in the safetensors metadata, not as extra sd keys.
        metadata = {"format": "pt"}
        if quant_layers:
            metadata["_quantization_metadata"] = json.dumps(
                {"layers": quant_layers})
        logging.info("scom merge: saving {}".format(path))
        comfy.utils.save_torch_file(out_sd, path, metadata=metadata)


NODE_CLASS_MAPPINGS = {"ScomMergeModel": ScomMergeModel}
NODE_DISPLAY_NAME_MAPPINGS = {"ScomMergeModel": "Merge Models (scom)"}
'''


def ensure_custom_nodes(paths: config.AppPaths) -> Path:
    """Write (or refresh) the scom custom node file; return its directory."""
    node_dir = paths.user_data / "custom_nodes"
    node_dir.mkdir(parents=True, exist_ok=True)
    node_file = node_dir / "scom_merge.py"
    # Rewrite only on change so an unchanged app doesn't churn the mtime.
    try:
        if node_file.read_text(encoding="utf-8") == NODE_SOURCE:
            return node_dir
    except OSError:
        pass
    node_file.write_text(NODE_SOURCE, encoding="utf-8")
    return node_dir
